# ベースイメージの設定
FROM ubuntu:17.10

# Nginx のインストール
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install nginx

# ポートの設定
EXPOSE 80

# Web コンテンツの配置
ONBUILD AND website.tar /var/www/html/

# Nginxの実行
CMD ["nginx", "-g", "daemon off;"]